{"uuid": "076ae06b-ec67-4212-824b-92678b726d34", "children": ["551cb4ae-90c6-4fa3-9323-45ebe8fc999b"], "befores": [{"name": "browserInstance", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n\tGetHandleVerifier [0x0x7ff7f6581eb5+80197]\n\tGetHandleVerifier [0x0x7ff7f6581f10+80288]\n\t(No symbol) [0x0x7ff7f63002fa]\n\t(No symbol) [0x0x7ff7f633f87b]\n\t(No symbol) [0x0x7ff7f6339bd0]\n\t(No symbol) [0x0x7ff7f638e0ef]\n\t(No symbol) [0x0x7ff7f638d870]\n\t(No symbol) [0x0x7ff7f6380153]\n\t(No symbol) [0x0x7ff7f6348b02]\n\t(No symbol) [0x0x7ff7f63498d3]\n\tGetHandleVerifier [0x0x7ff7f683e83d+2949837]\n\tGetHandleVerifier [0x0x7ff7f6838c6a+2926330]\n\tGetHandleVerifier [0x0x7ff7f68586c7+3055959]\n\tGetHandleVerifier [0x0x7ff7f659cfee+191102]\n\tGetHandleVerifier [0x0x7ff7f65a50af+224063]\n\tGetHandleVerifier [0x0x7ff7f658af64+117236]\n\tGetHandleVerifier [0x0x7ff7f658b119+117673]\n\tGetHandleVerifier [0x0x7ff7f65710a8+11064]\n\tBaseThreadInitThunk [0x0x7ffe77bfe8d7+23]\n\tRtlUserThreadStart [0x0x7ffe7972c53c+44]\n\n", "trace": "  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sachin Kumar Tiwari\\PycharmProjects\\ParaBank_Testing\\conftest.py\", line 26, in browserInstance\n    driver = webdriver.Chrome(service=ChromeService(), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Sachin Kumar Tiwari\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1760509721865, "stop": 1760509730859}], "start": 1760509721865, "stop": 1760509731270}