{"name": "test_Transaction_for_date", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'Schemas/transaction_schema.json'", "trace": "def test_Transaction_for_date():\n        Account_id = 36321\n        from_date = \"16-10-2025\"\n        to_date = \"16-10-2025\"\n        response = TRANSACTION_FOR_DATE.transaction_for_date(Account_id, from_date, to_date)\n    \n        assert response.status_code == 200, f\"Expected 200, got {response.status_code}\"\n    \n        response_json = response.json()\n    \n        # Load schema\n>       with open(\"Schemas/transaction_schema.json\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'Schemas/transaction_schema.json'\n\nTests\\API_Testing\\GET_TESTING\\test_transaction_for_date_range.py:17: FileNotFoundError"}, "start": 1760688094439, "stop": 1760688095932, "uuid": "f9960d8e-140a-4522-8cc9-bc9f14ebeb47", "historyId": "dee4e5b75657422975f0966e946d48a9", "testCaseId": "dee4e5b75657422975f0966e946d48a9", "fullName": "Tests.API_Testing.GET_TESTING.test_transaction_for_date_range#test_Transaction_for_date", "labels": [{"name": "parentSuite", "value": "Tests.API_Testing.GET_TESTING"}, {"name": "suite", "value": "test_transaction_for_date_range"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "28880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.API_Testing.GET_TESTING.test_transaction_for_date_range"}], "titlePath": ["Tests", "API_Testing", "GET_TESTING", "test_transaction_for_date_range.py"]}