{"name": "test_register_user", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 'Error!\n  The username and password could not be verified.' but got: 'Error!\n  An internal error has occurred and has been logged.'\nassert 'Error!\\nAn i... been logged.' == 'Error!\\nThe ... be verified.'\n  \n    Error!\n  - The username and password could not be verified.\n  + An internal error has occurred and has been logged.", "trace": "browserInstance = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"1aa96cb1a0a658db98cdae18264db2e1\")>\n\n    @pytest.mark.smoke\n    def test_register_user(browserInstance):\n        driver = browserInstance\n        driver.get(\"https://parabank.parasoft.com/parabank/index.htm\")\n        browserInstance.maximize_window()\n        wrong_user_login = wrong_user(browserInstance)\n        wrong_user_login.wrong_userID(user_data[\"wrong_username\"])\n        wrong_user_login.wrong_password(user_data[\"wrong_password\"])\n        wrong_user_login.click_on_submit()\n        time.sleep(4)\n        Error_note = f\"Error!\\nThe username and password could not be verified.\"\n    #Error!\n    \n        # Assertion\n        Error_message = wrong_user_login.error_message()\n>       assert Error_message.strip() == Error_note.strip(), \\\n            f\"Expected '{Error_note}' but got: '{Error_message}'\"\nE       AssertionError: Expected 'Error!\nE         The username and password could not be verified.' but got: 'Error!\nE         An internal error has occurred and has been logged.'\nE       assert 'Error!\\nAn i... been logged.' == 'Error!\\nThe ... be verified.'\nE         \nE           Error!\nE         - The username and password could not be verified.\nE         + An internal error has occurred and has been logged.\n\nTests\\test_login_with_wrong_user.py:33: AssertionError"}, "attachments": [{"name": "screenshot_on_failure", "source": "ded89d2a-3c6f-468d-8e67-5c59f4561694-attachment.png", "type": "image/png"}], "start": 1758269242687, "stop": 1758269260717, "uuid": "a807ab8a-a0bd-4d67-8304-ed459aedfc22", "historyId": "3015fe00414cb8653ce50973523d5c64", "testCaseId": "3015fe00414cb8653ce50973523d5c64", "fullName": "Tests.test_login_with_wrong_user#test_register_user", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login_with_wrong_user"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "8508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login_with_wrong_user"}], "titlePath": ["Tests", "test_login_with_wrong_user.py"]}